"""Themeable tab/window icons for the Qt UI.

The LxveLabs/CC monochrome icon set (``assets/icons/*.svg``, generated by ``assets/gen_icons.py``) is authored
with ``stroke="currentColor"`` so a single set serves any accent. PyQt5's ``QIcon`` does NOT honour
``currentColor`` on a plain ``QIcon(path)`` (it rasterises the file as-authored), so we substitute the accent
into the SVG text at load time and render it through ``QSvgRenderer`` — one helper, correct tint in any theme.

Wiring kit + tab→icon map: ``command-center/projects/cc-app/CC-ICON-WIRING-2026-07-08.md`` (prepared by mmrla).
"""
from __future__ import annotations

from PyQt5.QtCore import QByteArray, Qt
from PyQt5.QtGui import QIcon, QPainter, QPixmap
from PyQt5.QtSvg import QSvgRenderer

from src.core.resources import resource_path
from src.ui.qt.theme.colors import ACCENT  # brand accent — single source of truth (colors.py)

# The icons are monochrome + currentColor-driven, so re-tinting for a different theme is a one-arg change
# at the call site; the default tint is the brand ACCENT from colors.py above.

# Tab / surface label -> icon basename (from the wiring kit's 1:1 map). Used both for direct wiring and for the
# detached-tab restore path, so a tab keeps its icon after being popped out and back in.
TAB_ICONS = {
    "Connect": "connect",
    "Operate": "operate",
    "Network": "network",
    "Settings": "settings",
    "Devices": "devices",
    "Device View": "device-view",
    "Firmware": "firmware",
    "Flash": "flash",
    "Software OS": "software-os",
    "Nodes": "nodes",
    "Cross-Comm": "cross-comm",
    "Broadcast": "broadcast",
    "Health": "health",
    "Macros": "macros",
    "Targets": "targets",
    "Wardrive": "wardrive",
    "Multi-Wardrive": "multi-wardrive",
    "Flock Map": "flock-map",
    "Crack Lab": "crack-lab",
    "Graph": "graph",
    "Remote": "remote",
}


def tab_icon(name: str, color: str = ACCENT, px: int = 20) -> QIcon:
    """Return a QIcon for ``assets/icons/<name>.svg`` tinted with *color*. Empty QIcon (never a crash) if the
    file is missing/unreadable — a dropped asset degrades to a text-only tab, it doesn't take the UI down."""
    try:
        path = resource_path("assets", "icons", f"{name}.svg")
        svg = path.read_text(encoding="utf-8").replace("currentColor", color)
        renderer = QSvgRenderer(QByteArray(svg.encode("utf-8")))
        if not renderer.isValid():
            return QIcon()
        pm = QPixmap(px, px)
        pm.fill(Qt.transparent)
        painter = QPainter(pm)
        renderer.render(painter)
        painter.end()
        return QIcon(pm)
    except Exception:  # noqa: BLE001 — a bad/missing icon must never break tab construction
        return QIcon()


def label_icon(label: str, color: str = ACCENT, px: int = 20) -> QIcon:
    """Icon for a tab *label* via :data:`TAB_ICONS` (empty QIcon for an unmapped label). Lets the dynamic
    detached-tab restore path re-attach the right icon by label."""
    name = TAB_ICONS.get(label)
    return tab_icon(name, color, px) if name else QIcon()
